name: Building and Deplying Websocket Server
run-name: ${{ github.actor }} is building and deploying websocket server
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the code"
        uses: actions/checkout@v2

      - name: "Docker Login"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: spacecentre/ci-cd-deployments-testing-websocket:${{ github.sha }}

      - name: "Deploy to the VM"
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@139.59.71.37 -t "docker stop user_ws && docker rm user_ws && docker run --name user_ws -e DATABASE_URL=${{ secrets.DATABASE_URL }} -d -p 8080:8080 spacecentre/ci-cd-deployments-testing-websocket:${{ github.sha }}"
